Add badges
elenachekhina/test-guru pull request #17
Opened 2023-03-05 14:58 UTC by elenachekhina

2023-03-06 03:52 UTC, VidgarVii requested changes

2023-03-06 03:52 UTC, VidgarVii commented on app/controllers/admin/rules_controller.rb
> +  end
Если для сохранения объекта подразумевается сложная логика, то лучше использовать для этого отдельный сервис.

2023-03-06 03:52 UTC, VidgarVii commented on app/controllers/admin/rules_controller.rb
> +    @rule.type = params[:type]
1 Нарушение принципа Open/closed https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%B8%D0%BD%D1%86%D0%B8%D0%BF_%D0%BE%D1%82%D0%BA%D1%80%D1%8B%D1%82%D0%BE%D1%81%D1%82%D0%B8/%D0%B7%D0%B0%D0%BA%D1%80%D1%8B%D1%82%D0%BE%D1%81%D1%82%D0%B8
2 А если надо будет еще десяток правил ввести в проект? Что станет с кодом?

2023-03-06 03:52 UTC, VidgarVii commented on app/models/rule.rb
> +end
очень грязная модель. В идеале модель должна работать только с данными своей таблицы. Тут всё перемешана. Получается логика получения баджа размазана по проекту в место того чтобы её аккумулировать в одном месте

2023-03-06 03:52 UTC, VidgarVii commented on app/models/rule_first_time.rb
> +class RuleFirstTime < Rule
идея верная, реализация нет.
Классы Rule не могут быть моделями. Они не хранят данные.
Не стоит в папке модели делать свалку

2023-03-06 03:52 UTC, VidgarVii commented on app/models/test_passage.rb
> +    100 * self.correct_questions.to_d / total_questions
to_f

2023-03-06 03:52 UTC, VidgarVii commented on app/controllers/admin/rules_controller.rb
> +    params.require(:rule).permit(:success, :type, :category, :level, :from_first_time)
для всех правил можно ограничиться всего 2мя полями

2023-03-06 03:52 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +    @badges = Badge.check_badges(@test_passage)
в данном решении можно постоянно обновлять данную страницу результата и получать баджи. Либо нагружать систему. 
Бадж следует выдавать после завершения теста. А он завершается не тут

2023-03-13 06:48 UTC, VidgarVii requested changes

2023-03-13 06:48 UTC, VidgarVii commented on app/controllers/admin/badges_controller.rb
> +    params.require(:badge).permit(:title, :rule_type, :image, :category_id, :level)
ошибка в проектировании самой таблицы. При заполнении таблицы у тебя получится почти пусты колонки :level, :category_id
Такой подход считается очень плохим. Если колонка почти всегда пустая, то скорей всего она не нужна
Так же с таким подходом при увеличении правил придется каждый раз делать миграцию с добавлением этих полей

2023-03-13 06:48 UTC, VidgarVii commented on app/controllers/admin/badges_controller.rb
> +  def badge_param
не совсем понятно зачем отделять методы badge_rule_param и badge_param

2023-03-13 06:48 UTC, VidgarVii commented on app/helpers/tests_helper.rb
> +  }.freeze
коллекция у которых индекс является целое число называется массив

2023-03-13 06:48 UTC, VidgarVii commented on app/models/test.rb
> +  scope :questions, ->(id) { where(id:).questions }
нарушение соглашение скоупов. Скоупы должне возвращать только коллекцию того класса у которой он вызывается. Иначе нельзя будет строить цепочки запросов из скоупов

2023-03-13 06:48 UTC, VidgarVii commented on app/services/badge_service.rb
> +end
No new lina at end of file пора научиться избегать

2023-03-13 06:48 UTC, VidgarVii commented on app/services/badge_service.rb
> +        RULE_TYPES[badge.rule_type.to_sym].new(badge.category_id, badge.level, @test_passage).satisfied?
а теперь представим что у нас 100 типов правил и у каждого своя опция

2023-03-13 06:48 UTC, VidgarVii commented on app/services/rules/rule.rb
> +
такое кол-во отступов излишне. Используй рубокоп

2023-03-18 13:51 UTC, VidgarVii requested changes

2023-03-18 13:51 UTC, VidgarVii commented on app/controllers/admin/badges_controller.rb
> +    @badge.update(rule_parameters)
при обновлении ресурса надо так же проверять валидацию ресурса. Т.е. экшен должен быть оформлен по аналогии с create

2023-03-18 13:51 UTC, VidgarVii commented on app/controllers/admin/badges_controller.rb
> +                                                                                                     :level).to_json })
это всё усложняет код и делает не нужную работу. Пересмотри ролик который я скидывал ранее. Там всё рассказано про текущий момент

2023-03-18 13:51 UTC, VidgarVii commented on app/services/rules/rule.rb
> +    @level = rule_params['level'].present? ? rule_params['level'].to_i : nil
нет смысла в конструкторе создавать кучу переменных по названию параметра баджа. Проблема большого кол-ва баджей так и не решена.
Посмотри ролик!

2023-03-18 14:43 UTC, elenachekhina commented on app/services/rules/rule.rb
> +    @level = rule_params['level'].present? ? rule_params['level'].to_i : nil
@VidgarVii 
я не понимаю почему не решена, если использовать тут duck type, то какая разница от кого наследуются текущие правила, все равно в словаре захардкожены классы правил? в конкретно этом случае если так делать то это надо создавать еще одну абстракцию над классом Rule. конкретно эти типы правил можно наследовать от Rule, другие типы правил будут иметь скорее всего свой родительский класс, если надо

2023-03-18 14:44 UTC, elenachekhina commented on app/controllers/admin/badges_controller.rb
> +                                                                                                     :level).to_json })
@VidgarVii с тем условием, что в ролике это одиночные параметры для правила, а тут составные, как мне тогда лучше их хранить и передавать если я хочу одновременно задействовать и категорию и уровень, например?

2023-03-20 12:01 UTC, VidgarVii commented on app/controllers/admin/badges_controller.rb
> +                                                                                                     :level).to_json })
Не совсем понятно про составные параметры? Что это значит? У баджа есть тип правила и опция. Т.е. уровень или ид категории. Но не всё сразу вместе.

2023-03-20 12:03 UTC, VidgarVii commented on app/services/rules/rule.rb
> +    @level = rule_params['level'].present? ? rule_params['level'].to_i : nil
При чем тут duck type? Конструктор тут порождает кучу пустых переменных. И такие переменные будут увеличиваться с добавлением новых правил. Об этом я говорил в ролике

2023-03-27 06:34 UTC, VidgarVii commented on app/services/rules/rule_first_time_category.rb
> +  def checkout
предикатные методы принято называть со знаком вопроса.
checkout?

2023-03-27 06:44 UTC, merged