Lesson 4: Associations
elenachekhina/test-guru pull request #4
Opened 2022-11-18 08:16 UTC by elenachekhina

2022-11-18 13:04 UTC, VidgarVii commented on app/models/category.rb
> +  has_many :tests
если категорию удалить, то в текущем варианте можно в дальнейшем получить ошибку

к примеру при попытке обратиться по ассоциации (`@test.category`)
или при каких-то операциях, которые подразумевают валидацию объекта

после удаления категории в таблице `tests` останется в поле `category_id` ссылка на несуществующий объект
т.е. объекты в таблице `tests` станут невалидными: рельсы по умолчанию проверяют наличие ассоциированного объекта для всех `belongs_to` ассоциаций (при валидации этого объекта) и выбрасывают ошибку валидации, если объекта не существует

если же на уровне бд поле `category_id` обозначено, как внешний ключ, то уже на попытке удаления объекта из таблицы `categories` получим ошибку базы данных, такого примерно вида:
```
ActiveRecord::InvalidForeignKey (PG::ForeignKeyViolation: EROR:  update or delete on table "categories" violates foreign key constraint
```
и рельсы откажутся удалять категорию

поэтому для всех `has_*` ассоциаций следует указывать поведение при удалении - можно посмотреть в документации - опция `dependent: ...`

2022-11-18 13:04 UTC, VidgarVii commented on app/models/answer.rb
> +  has_many :answers
belongs_to и has_many разделяют пустыми строками. Такое разделение кода на логические блоки.
Пример оформления модели можно посмотреть тут https://github.com/rubocop/rails-style-guide#macro-style-methods

2022-11-18 13:04 UTC, VidgarVii commented on app/models/test.rb
> +  belongs_to :author, foreign_key: 'author_id', class_name: 'User'
Еще одно нарушение style guide
Надо соблюдай очередность.
Принято сначала писать belongs_to далее ниже has_
Так мы будем понимать какой код где находится
Пример оформления модели
https://github.com/rubocop-hq/rails-style-guide#macro-style-methods

2022-11-18 13:04 UTC, VidgarVii commented on app/models/test.rb
>        joins('JOIN categories on categories.id = tests.category_id')
с использованием ассоциации `joins` можно сильно сократить
в задании "Ассоциации моделей" самое время это сделать

***
```ruby
  joins(:category)
    .where(categories: { title: category_title })
    .order(title: :desc)
    .pluck(:title)

2022-11-18 13:04 UTC, VidgarVii commented on app/models/user.rb
>      TestsResult.where(user_id: self.id)
здесь в методе можно значительно упростить код
у тебя теперь есть ассоциация, которая вернет список всех тестов пользователя

по ТЗ надо возвращать тесты, а не TestsResult

2022-11-18 13:04 UTC, VidgarVii commented on app/models/user.rb
>      TestsResult.where(user_id: self.id)
так же в сидах теперь, благодаря ассоциациям, можно (и рекомендуется в ООП) передавать объекты для связывания по ключам, вместо аттрибутов: `category: categories[0]`, `author: users[0]` и т.п. (без `_id` , `.id`)

2022-11-18 18:08 UTC, elenachekhina commented on app/models/user.rb
>      TestsResult.where(user_id: self.id)
добрый вечер! не поняла про сиды что имеете в виду

2022-11-19 11:07 UTC, VidgarVii requested changes

2022-11-19 11:07 UTC, VidgarVii commented on app/models/category.rb
> +  has_many :tests, dependent: :nullify
belongs_to :category, без опции option в тестах и констрейн null false в схеме бд говорит, что тест не может быть без категории.
тоже самое замечание ниже по коду, где стоит опция nullify
Не корректно иметь в базе вопросы без теста, И тесты без автора и категорий

2022-11-20 07:01 UTC, VidgarVii requested changes

2022-11-20 07:01 UTC, VidgarVii commented on app/models/test.rb
> +              .pluck(:title)
Сейчас метод вернёт названия категорий, а надо название тестов

2022-11-21 05:41 UTC, VidgarVii requested changes

2022-11-21 05:41 UTC, VidgarVii commented on app/models/test.rb
>      end
```ruby
  joins(:category)
    .where(categories: { title: category_title })
    .order(title: :desc)
    .pluck(:title)
```

2022-11-21 05:41 UTC, VidgarVii commented on app/models/user.rb
>    def tests_of_level(level)
м/у методами и остальным кодом, надо оставлять пустую строку
используй gem rubocop для стилистической проверки кода

2022-11-21 05:41 UTC, VidgarVii commented on app/models/user.rb
>    def tests_of_level(level)
не исправлен файл с сидами

2022-11-21 05:42 UTC, VidgarVii commented on app/models/user.rb
>      TestsResult.where(user_id: self.id)
в сидах установка связей происходит с указанием ид объектов.
category_id: categories[0].id
Ассоциации позволяют писать код чище и логичней. Без Ид
category: categories[0]

2022-11-21 06:38 UTC, elenachekhina commented on app/models/user.rb
>    def tests_of_level(level)
я использовала, но что с новой строкой что без, для этого файла он ругается только на Missing top-level documentation comment и Missing frozen string literal comment. может он как-то неправильно настроен? хотя конфиг файлы я не добавляла для рубокопа

2022-11-21 18:22 UTC, merged